version: '3.4'

services:
    db:
        image: postgres
        restart: always
        build:
            context: .
            dockerfile: docker_files/Dockerfile
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: clinicadb
        ports:
            - "5432:5432"
        networks:
            - home-network
            
    clinica.webapi:
        image: clinica-webapi
        build:
          context: .
          dockerfile: Clinica.WebApi/Dockerfile
        environment:
           TZ: America/Sao_Paulo
           ASPNETCORE_ENVIRONMENT: Production
        ports:
            - "5000:80"
        depends_on:
            - db
        networks:
            - home-network
            
networks:
    home-network:
        driver: bridge
